---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    app: {{ include "collector.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "collector.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "collector.name" . }}
    spec:
      volumes:
        - name: otel-collector-config
          configMap:
            name: {{ include "collector.fullname" . }}-config
            items:
              - key: otel-config.yaml
                path: otel-config.yaml
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          command:
            - {{ .Values.otelCollector.command }}
            - "--config={{ .Values.otelCollector.configPath }}"
          ports:
            {{- range .Values.otelCollector.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          volumeMounts:
            - name: otel-collector-config
              mountPath: {{ .Values.otelCollector.configMountPath }}
          livenessProbe:
            httpGet:
              path: {{ .Values.otelCollector.livenessProbe.path }}
              port: {{ .Values.otelCollector.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.otelCollector.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.otelCollector.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.otelCollector.readinessProbe.path }}
              port: {{ .Values.otelCollector.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.otelCollector.readinessProbe.initialDelaySeconds }}
