---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    app: {{ include "collector.name" . }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  selector:
    app: {{ include "collector.name" . }}
  ports:
    {{- range .Values.otelCollector.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
