receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

processors:
  batch:
    timeout: 200ms

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
